### ISSUE TITLE
Debug option not working

### ISSUE THREAD

**Issue by lushohammy** [AugustToko/ACG-Player#10]
**Describe the bug**
Acg Player back icon and sahre button not working in Debug option

**To Reproduce**
1. open the app
2. click on Debug option
3. note the bug

**Expected behavior**
it expected that user should use Debug option

**Smartphone:**
 - Android 8.1.0
 - app v2.6.2.5

**Recording Of The Bug:**
https://youtu.be/1wWWtuzAzjc

**Comment by AugustToko** [comment]
This will be removed in the next version.
Thank you for your report.
