### ISSUE TITLE
(BUG) Found in ACG-Player  Data clear option is not working properly

### ISSUE THREAD

**Issue by facebook-786** [AugustToko/ACG-Player#11]
# Project Information

* Repository: https://github.com/AugustToko/ACG-Player
* Project Name:  ACG-Player

# Expected behavior

When I try to clear the data used in the application, the data should be removed from the application

# Actual behavior

When I try to clear the data used in the application, that data does not remove the application but still remains in the application.

# How to reproduce

1-[Download ](https://github.com/AugustToko/ACG-Player/releases)the app and open it
2-Click on the three horizontal lines on the top left
3- go to More info Option
4-Click the Data clear  icon at the bottom right
5-click on sure
6- see bug

* Browser/App version: 2.6.2.5
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190524_180516](https://user-images.githubusercontent.com/50115498/58329707-0a4abc00-7dea-11e9-950e-617be7e2e9b3.gif)

# My Github Account
https://github.com/facebook-786

**Comment by AugustToko** [comment]
Fixed in this commit

**Comment by friendsmobile** [comment]
bug fixed  now
