### ISSUE TITLE
bug in more info option

### ISSUE THREAD

**Issue by lushohammy** [AugustToko/ACG-Player#12]
**Describe the bug**
More info option not working and app crashes when playing a song after click on More info option .

**To Reproduce**
1. open the app
2. go to a song More info option
3. then try to play a music
4. and show app crasshes 

**Expected behavior**
it expected that user click on More info option for more dtails about song and i would not be crashes after click on More info option .

**Smartphon:**
 - OS: Android 8.1.0
 - appVersion 2.6.2.5 

**Recording Of The Bug:**
https://youtu.be/SHJ1cRYs3Jk

**Comment by AugustToko** [comment]
Has been fixed in the next release. thx for report
