### ISSUE TITLE
[ACG Player][2.6.2 ]The application crashes if I click on show Album

### ISSUE THREAD

**Issue by 44asad** [AugustToko/ACG-Player#13]
### 
Expected behavior
The application should not crash when I click "show album

### Actual behavior:
The application is crash when I click "show album option.

### How to reproduce
* Install the apps and open the app
* Navigate to playlist
* click no show album
* Then 2-3 step click.
* See the error
### Information
App version:v2.6.2
OS:Android 6.0.1
Device:Samsung j5
### Recording Of The Bug

https://youtu.be/RCQKDgoIrvk
### Logcat:
<pre><code>05-24 04:18:30.425  8846  8846 E AndroidRuntime: FATAL EXCEPTION: main
05-24 04:18:30.425  8846  8846 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 8846
05-24 04:18:30.425  8846  8846 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
05-24 04:18:30.425  8846  8846 E AndroidRuntime:   at java.util.ArrayList.get(ArrayList.java:310)
05-24 04:18:30.425  8846  8846 E AndroidRuntime:   at h.a.a.b.b.Ea.a(SourceFile:58)
05-24 04:18:30.425  8846  8846 E AndroidRuntime:   at h.a.a.b.b.l.onClick(lambda)
05-24 04:18:30.425  8846  8846 E AndroidRuntime:   at android.view.View.performClick(View.java:5698)
05-24 04:18:30.425  8846  8846 E AndroidRuntime:   at android.view.View$PerformClick.run(View.java:22565)
05-24 04:18:30.425  8846  8846 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:739)
05-24 04:18:30.425  8846  8846 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:95)
05-24 04:18:30.425  8846  8846 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
05-24 04:18:30.425  8846  8846 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7231)
05-24 04:18:30.425  8846  8846 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
05-24 04:18:30.425  8846  8846 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-24 04:18:30.425  8846  8846 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)</code></pre>

**Comment by 44asad** [comment]
@AugustToko
pleased review?

**Comment by AugustToko** [comment]
Fixing, are other albums working properly?

**Comment by 44asad** [comment]
but not working  my devices.

**Comment by 44asad** [comment]
@AugustToko
new version 2.6.3 same problem. please  review?

**Comment by AugustToko** [comment]
> @AugustToko
> new version 2.6.3 same problem. please review?

Wait a moment, I will recheck my code right away.

**Comment by 44asad** [comment]
@AugustToko
??

**Comment by AugustToko** [comment]
> @AugustToko
> ??

I am very sorry to reply so late, I will try to fix it tomorrow, because this problem is a special case on individual devices.
