### ISSUE TITLE
(BUG) Found in ACG-Player  After clicking on the More info option, the application crashes when I click the song title

### ISSUE THREAD

**Issue by saraji-ali** [AugustToko/ACG-Player#14]
# Project Information

* Repository: https://github.com/AugustToko/ACG-Player
* Project Name:  ACG-Player
* My issue: https://github.com/AugustToko/ACG-Player/issues/14

# Expected behavior

After clicking on the More info option, click on a Song title when the app should not crash.

# Actual behavior

After clicking More info then I click on song title the application crashes

# How to reproduce

1-[Download ](https://github.com/AugustToko/ACG-Player/releases)the app and open it
2- Go to Artist TAB
3-click on 3 vertical dots 
4-Click on the Nextplay tool
5-Click the song title
6- see bug

* Browser/App version: 2.6.2.5
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190524_162340](https://user-images.githubusercontent.com/50115498/58324657-58f15980-7ddc-11e9-8280-24505e4774a4.gif)

# My Github Account
https://github.com/saraji-ali

# Logcat

<pre><code>/AndroidRuntime(20690): FATAL EXCEPTION: main

E/AndroidRuntime(20690): Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 20690

E/AndroidRuntime(20690): java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.recyclerview.widget.RecyclerView$a._d(int)' on a null object reference

E/AndroidRuntime(20690): 	at top.geek_studio.chenlongcould.musicplayer.activity.ListViewActivity$a.handleMessage(SourceFile:2)

E/AndroidRuntime(20690): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(20690): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(20690): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(20690): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(20690): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(20690): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(20690): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by lushohammy** [comment]
where is the dtails ?

**Comment by facebook-786** [comment]
@lushohammy  thanks  your information

**Comment by AugustToko** [comment]
This issue has been fixed and you can check it in the new version.

**Comment by AugustToko** [comment]
On the release page

**Comment by friendsmobile** [comment]
bug fixed  now
