### ISSUE TITLE
(BUG) Found in ACG-Player The app crashes when I click multiple times on the song running in the History (Ram) tab

### ISSUE THREAD

**Issue by saraji-ali** [AugustToko/ACG-Player#15]
# Project Information

* Repository: https://github.com/AugustToko/ACG-Player
* Project Name:  ACG-Player

# Expected behavior

When I go to History (Ram) tab and click multiple times on the song title, then the app should not crash.

# Actual behavior

the app crashes when I click multiple times on the song running in the History (Ram) tab

# How to reproduce

1-[Download ](https://github.com/AugustToko/ACG-Player/releases)the app and open it
2- go to PLAY LIST
3- click on the History (RAM)
4- Click multiple times on the running songs

* Browser/App version: 2.6.2.5
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190524_170935](https://user-images.githubusercontent.com/50115498/58326797-b7213b00-7de2-11e9-88f6-ab1f5993e6d4.gif)

# My Github Account
https://github.com/saraji-ali

# Logcat

<pre><code>E/AndroidRuntime(32683): FATAL EXCEPTION: main

E/AndroidRuntime(32683): Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 32683

E/AndroidRuntime(32683): java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.recyclerview.widget.RecyclerView$a._d(int)' on a null object reference

E/AndroidRuntime(32683): 	at top.geek_studio.chenlongcould.musicplayer.activity.ListViewActivity$a.handleMessage(SourceFile:2)

E/AndroidRuntime(32683): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(32683): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(32683): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(32683): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(32683): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(32683): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(32683): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by AugustToko** [comment]
Try it in the new version

**Comment by friendsmobile** [comment]
bug fixed  now
