### ISSUE TITLE
(BUG) Found in ACG-Player When I click two or more times on verticale dot, the application is crashed

### ISSUE THREAD

**Issue by saraji-ali** [AugustToko/ACG-Player#16]
# Project Information

* Repository: https://github.com/AugustToko/ACG-Player
* Project Name:  ACG-Player

# Expected behavior

When I click 3 verticle dots, the option should appear and the application should not crash

# Actual behavior

When I click two or more times on vertical dot, the application is crashed

# How to reproduce

1-[Download ](https://github.com/AugustToko/ACG-Player/releases)the app and open it
2- go to Album Tab
3-click on 2 time or 3 time on 3 verticle dots
4- see bug 

* Browser/App version: 2.6.2.5
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190524_165841](https://user-images.githubusercontent.com/50115498/58326184-ef277e80-7de0-11e9-919b-2323bb9400ae.gif)

# My Github Account
https://github.com/saraji-ali

# Logcat

<pre><code>E/AndroidRuntime(28545): FATAL EXCEPTION: main

E/AndroidRuntime(28545): Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 28545

E/AndroidRuntime(28545): java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.recyclerview.widget.RecyclerView$a._d(int)' on a null object reference

E/AndroidRuntime(28545): 	at top.geek_studio.chenlongcould.musicplayer.activity.ListViewActivity$a.handleMessage(SourceFile:2)

E/AndroidRuntime(28545): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(28545): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(28545): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(28545): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(28545): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(28545): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(28545): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by AugustToko** [comment]
Try the new version, maybe fix this bug

**Comment by friendsmobile** [comment]
bug fixed  now
