### ISSUE TITLE
(BUG) Found in ACG-Player Donate button is not working properly 

### ISSUE THREAD

**Issue by facebook-786** [AugustToko/ACG-Player#17]
# Project Information

* Repository: https://github.com/AugustToko/ACG-Player
* Project Name:  ACG-Player

# Expected behavior

When I click on the donate option, the PayPal page should be open next to where the user can donation the money

# Actual behavior

Donate button is not working properly

# How to reproduce

1-[Download ](https://github.com/AugustToko/ACG-Player/releases)the app and open it
2-Click the 3 horizontal lines on the top left
3- click on Donate
4- see bug

* Browser/App version: 2.6.2.5
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190524_164228](https://user-images.githubusercontent.com/50115498/58325528-dae28200-7dde-11e9-887d-93fcbd4430b6.gif)

# My Github Account
https://github.com/facebook-786

**Comment by AugustToko** [comment]
The main logic of the donation function has been removed, but it still exists in navigation, it will be removed in the next version. 
Thank you for your report.

**Comment by facebook-786** [comment]
welcome sir

**Comment by AugustToko** [comment]
🤭
