### ISSUE TITLE
[ACG Player][2.6.2 ]The application crashes if I click on add play  "My Favorite"

### ISSUE THREAD

**Issue by qbrave1** [AugustToko/ACG-Player#18]
### Expected behavior
The application should not crash when I click "Add play list, My Favorite.

### Actual behavior:
The application is crash when I click "My favorite option.

### How to reproduce
* Install the apps and open the app
* Navigate to playlist
* click no Add Play List and 
* Click  My Favorite.
* See the error
### Information
App version:v2.6.2
OS:Android 6.0.1
Device:Samsung j7
### Recording Of The Bug

https://youtu.be/IWK39-NhFNU

### logcat

<pre><code>E/AndroidRuntime( 5296): FATAL EXCEPTION: main

E/AndroidRuntime( 5296): Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 5296

E/AndroidRuntime( 5296): java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3

E/AndroidRuntime( 5296): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)

E/AndroidRuntime( 5296): 	at java.util.ArrayList.get(ArrayList.java:308)

E/AndroidRuntime( 5296): 	at h.a.a.b.h.l.a(SourceFile:22)

E/AndroidRuntime( 5296): 	at h.a.a.b.h.e.onClick(lambda)

E/AndroidRuntime( 5296): 	at b.b.a.l.onItemClick(SourceFile:1)

E/AndroidRuntime( 5296): 	at android.widget.AdapterView.performItemClick(AdapterView.java:318)

E/AndroidRuntime( 5296): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1166)

E/AndroidRuntime( 5296): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)

E/AndroidRuntime( 5296): 	at android.widget.AbsListView$3.run(AbsListView.java:3943)

E/AndroidRuntime( 5296): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime( 5296): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime( 5296): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime( 5296): 	at android.app.ActivityThread.main(ActivityThread.java:5912)

E/AndroidRuntime( 5296): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime( 5296): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime( 5296): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime( 5296): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)</code></pre>

**Comment by AugustToko** [comment]
You can try the latest version on the release page. It should have been fixed
