### ISSUE TITLE
(BUG) Found in ACG-Player The option of favorite songs in the car mode does not work

### ISSUE THREAD

**Issue by facebook-786** [AugustToko/ACG-Player#19]
# Project Information

* Repository: https://github.com/AugustToko/ACG-Player
* Project Name:  ACG-Player

# Expected behavior

In the Car mode option, when I click on the Favorites Song icon, then the songs should be listed in the Favorites list.

# Actual behavior

The option of favorite songs in the car mode does not work

# How to reproduce
1-[Download ](https://github.com/AugustToko/ACG-Player/releases)the app and open it
2-Click the 3 horizontal lines on the top left
3- go to car Mode
4- Play a song and click the song favorite icon

* Browser/App version: 2.6.2.5
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190524_182424](https://user-images.githubusercontent.com/50115498/58330978-f785b680-7dec-11e9-82d8-4d797388770c.gif)

# My Github Account
https://github.com/facebook-786

**Comment by AugustToko** [comment]
Already fixed, including the trash can function. If it is not this issue I may forget this car mode (yes, as a developer)
