### ISSUE TITLE
Add Privacy Policy, FAQs and Contributor's guidelines. 

### ISSUE THREAD

**Issue by HarryHeights** [AugustToko/ACG-Player#20]
Hello, I'm Harry. I engage in creating documents for open source projects. It's part of my contribution to helping open source projects. One of the documents I engage in creating is a privacy policy. The privacy policy will give details about user information collection, use and security. I really don't know if you externally collect user information, but, if you don't, it's good to let end users know via a privacy policy.
Contributor's guidelines is also an important document that will help prospective collaborators contribute easily to your project.

I'll love to hear your thoughts on this.

**Comment by AugustToko** [comment]
Hello, I am still a student at school and a start-up developer. The documentation for the privacy policy is not known, and the current focus is on fixing bugs and adding new features.
I would be very grateful to those who contributed, including the issue.

**Comment by HarryHeights** [comment]
Oh okay. So I could go ahead and send PRs?

**Comment by AugustToko** [comment]
> Oh okay. So I could go ahead and send PRs?

sure

**Comment by HarryHeights** [comment]
Great! I'll send PRs for the privacy policy and contributor's guidelines very soon. For the FAQs, I can compile something before the end of today though. Thanks for letting me contribute.
