### ISSUE TITLE
ACG-Player cant open songs from google chorom

### ISSUE THREAD

**Issue by lushohammy** [AugustToko/ACG-Player#21]
**Expected behavior**
it expected that user can open songs from google chorom or google chorom downloaded folder

**Actual behavior**
i cant open songs from google chorom or google chorom downloaded folder and it shows me another player to open songs without ACG-Player

**How to reproduce**
 - OS: Android 8.1.0
 
 - ACG-Player App version: 2.6.2.5
 - Google chrome version: 74.0.3729.157

**Recording Of The Bug**
https://youtu.be/S7ZeHIuxrFU

**Comment by AugustToko** [comment]
Fixed, posted to release page later

**Comment by AugustToko** [comment]
already updated
