### ISSUE TITLE
App crashed after checking the song info and going back to click the song in the album

### ISSUE THREAD

**Issue by cckole** [AugustToko/ACG-Player#22]
**Describe the bug**
I played a song under music, clicked the `three dots` and clicked on `show album`. After the album showed up, I clicked on the three dots to check more info and returned back to the album by clicking the back arrow. When I then clicked on the song to make it start all over again, the app crashed.

**To Reproduce**
Steps to reproduce the behavior
1. Launch the app
2. play any song
3. Click on the three dots directly opposite the song played
4. Click on `Show album`
5. Click on the three dots directly opposite the same song in the album
6. Click `more info`
7, Click the back arrow
8. Tap the song you are playing and note the crash

**Expected behavior**
After checking the song info and clicking on the song, I expected it to start over again with the app still open, but it crashed instead,

**Reproducing the behaviour**
https://youtu.be/Cmvg90msqRM

**Device used**
 - Device: [Tecno spark k7]
 - OS: [Android 7.0]
 - App version [v.2.6.2]

**Comment by AugustToko** [comment]
You can try the latest version on the release page.

**Comment by cckole** [comment]
It's working well in the latest version. Nice work.
