### ISSUE TITLE
Song can't be deleted 

### ISSUE THREAD

**Issue by cckole** [AugustToko/ACG-Player#23]
**Describe the bug**
When i was playing a song, I decided to delete it and I tapped on the song to locate the delete icon. I then clicked on the delete icon and there was a pop up ordering me to drop the selected song to `trash can`, which I did by clicking on `Sure`, but the song wasn't deleted.

**To Reproduce**

1. Launch the app
2. Play the song you want to delete/ It will reflect below the app
3. Tap on it and look up on the app by the right side. You will see the delete icon
4. Click on it and click on sure
5. The song will keep playing and if you proceed to check whether it was deleted, you will still find it in the music list.

**Expected behavior**
After deleting the song, I expected it to stop playing and be totally deleted from the music list

**Reproducing the behaviour**
https://youtu.be/YZMAtub_avo

**Smartphone (please complete the following information):**
 - Device: [TECNO SPARK K7]
 - OS: [ANDROID 7.0]
 - Version [V.2.6.2]

**Comment by cckole** [comment]
Still cant delete song in the new version.

**Comment by AugustToko** [comment]
> Still cant delete song in the new version.

Sorry, I have not fixed this issue yet. This bug is my next goal.

**Comment by cckole** [comment]
Alright. Good job

**Comment by AugustToko** [comment]
fixed, We will release the next version

**Comment by AugustToko** [comment]
try new version
