### ISSUE TITLE
Setting song as ring tone isn't working

### ISSUE THREAD

**Issue by cckole** [AugustToko/ACG-Player#27]
**Describe the bug**
song not set as ring tone

**To Reproduce**
- launch the app
- click on the music image. You will see some optiond from the drop down
- Click on `set Ringtone`
- Notice the sound of your ringing tone when you recieve a call

**Expected behavior**
I expected the song I set as ringtone to play when I recieved a call.

**reproducing the behaviour**

https://youtu.be/WgQ1vmwWb4c  

**Smartphone 
 - Device: [Tecno spark K7]
 - OS: [Android 7.0]
 - App Version [2.6.3.1]New version
- Github link [https://github.com/AugustToko/ACG-Player/issues/27]

**Comment by AugustToko** [comment]
Since I didn't apply for the required permissions, it doesn't work properly on the high version system. I will fix it tomorrow.

**Comment by AugustToko** [comment]
Has been fixed, you can view it on the release page
