### ISSUE TITLE
[ACG Player][2.6.16 ]The application crashes if I click on  "Fast Play

### ISSUE THREAD

**Issue by 44asad** [AugustToko/ACG-Player#3]
#### Expected behavior
I expected that the app would not crash when I click on "Fast play"option.

### Actual behavior:
The application is crash when I click "Fast Play" option.

### How to reproduce:
* Download the app and open it
* Then 3-4 step click Fast Play option 
* after try to click 
* see bug
#### Recording Of The Bug:
https://youtu.be/jDxJyPJUmh0

#### Information
App version:v2.6.16
OS:Android 6.0.1
Device:Samsung J5

### Logcat:
<pre><code>05-23 08:44:32.182 32070 32530 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-23 08:44:32.182 32070 32530 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 32070
05-23 08:44:32.182 32070 32530 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at android.os.AsyncTask$3.done(AsyncTask.java:309)
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at java.lang.Thread.run(Thread.java:818)
05-23 08:44:32.182 32070 32530 E AndroidRuntime: Caused by: java.lang.IllegalStateException
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at android.os.Parcel.readException(Parcel.java:1628)
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at android.os.Parcel.readException(Parcel.java:1573)
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at top.geek_studio.chenlongcould.musicplayer.g$a$a.prepare(SourceFile:274)
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at top.geek_studio.chenlongcould.musicplayer.broadcasts.ReceiverOnMusicPlay.prepare(SourceFile:161)
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at top.geek_studio.chenlongcould.musicplayer.broadcasts.ReceiverOnMusicPlay$b.k(SourceFile:468)
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at top.geek_studio.chenlongcould.musicplayer.broadcasts.ReceiverOnMusicPlay$b.doInBackground(SourceFile:442)
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at android.os.AsyncTask$2.call(AsyncTask.java:295)
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-23 08:44:32.182 32070 32530 E AndroidRuntime:   ... 4 more</code></pre>

**Comment by AugustToko** [comment]
**Thank you very much for your issue.**
Due to my negligence, I did not release a new version on the release page.
You can go to this store to download https://www.coolapk.com/apk/209705
I will update on the release page later.

**Comment by 44asad** [comment]
new version  same problem.

**Comment by AugustToko** [comment]
This issue has been fixed and you can check it in the new version.
