### ISSUE TITLE
v2.6.3.2  Upadate Log  crash

### ISSUE THREAD

**Issue by lushohammy** [AugustToko/ACG-Player#30]
**Describe the bug**
when click on **Upadate Log** ACG player has stopped

**To Reproduce**

1. open the app
2. click on 3 horizontal line
3. go to About
4. then click on **Upadate Log**
5. note the bug

**Expected behavior**
it expect that user should use **Upadate Log** option without ctash

**Smartphone:**
 - Device: Xiaomi redmi 5
 - OS: v8.1.0
 
 - App Version : 2.6.3.2

**Recording Of The Bug:**
https://youtu.be/18G7Xwr1Vw0

**Comment by AugustToko** [comment]
Has been fixed, you can view it on the release page
