### ISSUE TITLE
Bug: play and other functions are overlapped by playing details later. 

### ISSUE THREAD

**Issue by darewealth** [AugustToko/ACG-Player#31]
**Describe the bug**

Whenever I play music on the app, the details of the music that shows below the music playing page overlap the play,  pause,  shuffle,  and repeat functions. Once a music is played,  there is no means to stop it again,  unless I switched off my phone.  

**To Reproduce**
1. Launch the app
2. Click on any music 
3.Scrol it up

**Expected behavior**

The overlapped layer blocked the functions, and I don't expect it to happen.  

**Screenshots**
https://youtu.be/XfgSn1LoP0c

**Smartphone 
* Device: [itel]
* OS: [6.1]
* Version 2.6.3.1(20190526)

**Comment by AugustToko** [comment]
Can you tell me the specific phone model?

**Comment by darewealth** [comment]
Itel (A11)

**Comment by AugustToko** [comment]
> Itel (A11)

I think he has been fixed and will be posted to the release page later.

**Comment by darewealth** [comment]
Good well done :+1:
