### ISSUE TITLE
Bug: App next  last played song when I re-launched and clicked on the play button 

### ISSUE THREAD

**Issue by darewealth** [AugustToko/ACG-Player#32]
**Describe the bug**

When I play any music on the app,  then I stop and exit the app for a while, when I launch again,  and try to  continue the music,  it does not play. But when I wipe up to play on a full-screen, it next the music. 

**To Reproduce**

1. Open the  app,  and play any music. 
2. Exit the app and wait for some minutes 
3.Launch the app again and try to play the music. 
4. Not the error

**Expected behavior**

I expect that I should be able to play without any issue.  

**Screenshot**
https://youtu.be/_GbWG-YakFA

**Smartphone**

* Device: [Gionee]
* OS: [7.0]
* Version 2.6.3.1(20190526)

**Comment by AugustToko** [comment]
Has been fixed, you can view it on the release page

**Comment by AugustToko** [comment]
By the way, it has been fixed that the music name is too long to display the abbreviated form.
