### ISSUE TITLE
 [V2.6.3.6] Crash when remove a theme 

### ISSUE THREAD

**Issue by lushohammy** [AugustToko/ACG-Player#33]
**Describe the bug**
when remove a theme and and click on theme again from the list the app crash

**To Reproduce**
1. go to **Theme** in the settings option
2. then click on any theme out of two 
3. then click on **Delete** and coinfirm with click on **SURE**
4. then click on again on this theme
5. note the bug

**Expected behavior**
it expected that user can remove theme smoothly and click on theme without any crash.

**Smartphone**
 - Device: xiaomi redmi 5
 - Browser/App version: v2.6.3.6
 - Operating system: Android 8.1.0

#### Recording Of The Bug:
https://youtu.be/7LrRuvyThyg

**Comment by AugustToko** [comment]
Fixed, posted to release page later

**Comment by AugustToko** [comment]
already updated
