### ISSUE TITLE
[V2.6.3.6] cant play songs from Device File manager

### ISSUE THREAD

**Issue by lushohammy** [AugustToko/ACG-Player#34]
**Describe the bug**
when try to playing songs from phone file manager with Acg player it nothing response

**To Reproduce**
1. go file manager
2. select a music 
3. then try to play with Acg player
4. show that it not response .

**Expected behavior**
it expected that i can listen music from my file manager with Acg player.

**Smartphone**
 - Device: xiaomi redmi 5
 - Browser/App version: v2.6.3.6
 - Operating system: Android 8.1.0

#### Recording Of The Bug:
https://youtu.be/eVyeUStl5v4

**Comment by AugustToko** [comment]
Fixed, posted to release page later
