### ISSUE TITLE
Bug: The equalizer feature does not work

### ISSUE THREAD

**Issue by darewealth** [AugustToko/ACG-Player#39]
**Describe the bug**

When I play music and scroll up the music details from the bottom of the app, then I tried to use the Equalizer, it pops up no equalizer. This feature works on Android 8.1.
**To Reproduce**

1. Launch the app
2. Click on any music
3.Scroll it up
4. Click on 3 dots at the top by the right 
5. Then click equalizer 
6. See error

**Expected behavior**
 
I expect to see and use the set of equalizer feature in the app.

**Screenshots**
https://youtu.be/w7pN9le1dxA

**Smartphone 
 - Device: [Gionee X1]
 - OS: [7.0]
 - Version 2.6.3.5(20190527)

**Comment by AugustToko** [comment]
This feature is called on the EQ app on your phone, if you don't have any natural response.

**Comment by cckole** [comment]
Hey @August Toko, I'm having the same issue here. The EQ is completely written and yet not responding. https://youtu.be/sRyskwpO06w. You can see the video.

**Comment by AugustToko** [comment]
> Hey @AugustToko , I'm having the same issue here. The EQ is completely written and yet not responding. https://youtu.be/sRyskwpO06w. You can see the video.

In fact, EQ can be considered a separate application, ACG player does not include it, this option knowledge points to the EQ program in your phone. If it doesn't exist, it will naturally not respond. I will add a few optional EQ program recommendations in the later stage (pointing to the PlayStore as a dialog box)

By the way, I recently optimized IPC (Process Communication) and will be releasing a new version recently.

**Comment by cckole** [comment]
Oh! Now I understand. No problems.  Will be expecting the new version. Well done.

**Comment by AugustToko** [comment]
Has been posted to the release page

**Comment by darewealth** [comment]
Thank you for the response. I just checked again in the recent release few hours ago and discovered that it has shown the equalizer without downloading on google play. It's now perfect.
