### ISSUE TITLE
[Acg Player][2.6.2]The app crashes if i click random play icon.

### ISSUE THREAD

**Issue by maaudrana** [AugustToko/ACG-Player#4]
<h4>Actual behavior</h4>
App crashes if i click on random play icon.
<h4>Expected behavior</h4>
Expected that i can play song randomly by clicking random play icon.
<h4>How to reproduce</h4>
<ol>
<li>Install the apps and open the app</li>
<li>Click playlist</li>
<li>choose a playlist and click on that.</li>
<li>Click the random play icon.</li>
<li>See the error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:v2.6.2</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/1iH-aD73yqg"> youtube.com</a>
<h4>Logcat</h4>
<pre><code>
05-24 15:28:01.892 20703 20703 E AndroidRuntime: FATAL EXCEPTION: main
05-24 15:28:01.892 20703 20703 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 20703
05-24 15:28:01.892 20703 20703 E AndroidRuntime: java.lang.IllegalArgumentException: bound must be positive
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at java.util.Random.nextInt(Random.java:388)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.activity.ListViewActivity.d(SourceFile:32)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at h.a.a.b.a.L.onMenuItemClick(Unknown Source:2)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(SourceFile:2)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(SourceFile:2)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at b.b.f.a.k.a(SourceFile:19)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at b.b.f.a.o.invoke(SourceFile:2)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at b.b.f.a.k.a(SourceFile:39)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at b.b.f.a.k.a(SourceFile:36)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at androidx.appcompat.widget.ActionMenuView.invokeItem(SourceFile:1)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(SourceFile:2)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at android.view.View.performClick(View.java:7339)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:14222)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7305)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at android.view.View.access$3200(View.java:846)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27788)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-24 15:28:01.892 20703 20703 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
</code>
</pre>

**Comment by maaudrana** [comment]
@AugustToko can i know why you added  duplicate lebel? Or can you add yhe reference?

**Comment by AugustToko** [comment]
> @AugustToko can i know why you added duplicate lebel? Or can you add the reference?

The logic of fast play and random play is the same.
This is a legacy issue and I will correct the name.
In addition, this logic has been fixed.

**Comment by maaudrana** [comment]
Oh but fast play working  fine in my device💪

**Comment by maaudrana** [comment]
So dear can you remove  the duplicate  lebel  now?

**Comment by AugustToko** [comment]
> So dear can you remove the duplicate lebel now?

ok and you can try the new version to solve your problem 
On the release page

**Comment by maaudrana** [comment]
Still fetching the same problem

**Comment by AugustToko** [comment]
> Still fetching the same problem
> I downloaded the latest version.

Ok, I got it wrong. I thought it was a random play of the main page. 😰It has been fixed.

**Comment by maaudrana** [comment]
Haha ,not need to be sad its ok

**Comment by maaudrana** [comment]
When ypu will release  the fixed  version

**Comment by AugustToko** [comment]
> When you will release the fixed version
Compiling, going to upload after a while

**Comment by maaudrana** [comment]
Ok waiting  for that to test it again😜

**Comment by AugustToko** [comment]
> Ok waiting for that to test it again😜

It is done
I am very grateful to you for taking the time to participate in this project.🙃

**Comment by maaudrana** [comment]
Omg! Its working  fine now.Great♥️♥️

**Comment by AugustToko** [comment]
> Omg! Its working fine now.Great♥️♥️

That's great, you can check it out by the way [https://github.com/AugustToko/ACG-Player/issues/8](url) ，It should also be fixed
