### ISSUE TITLE
Song is still present in the playlist even if you move it to trash

### ISSUE THREAD

**Issue by crysports** [AugustToko/ACG-Player#46]
I clicked on the delete option on the top right corner of the application. I was expecting that the song will be deleted from the playlist and moved to trash.
The song was moved to trash but it was still present in the playlist and playable as well.
The song should no longer be accessed in the playlist if it is moved to the trash.

https://youtu.be/xeiVFChFl-Q

**Comment by AugustToko** [comment]
You can set the blacklist on the settings page, or click Add to black list in the menu.
This feature will be added in the next release.
