### ISSUE TITLE
Delete option does not work

### ISSUE THREAD

**Issue by crysports** [AugustToko/ACG-Player#47]
After moving some songs to the trash I tried to delete them but the delete option simply didn't work for me.
Long pressing on a song in trash folder will select the song and you can perform actions. After long pressing, I clicked on menu on top right corner and clicked on delete option but the song was not deleted.
https://youtu.be/U5bjMfoAIk0

**Comment by AugustToko** [comment]
fixed, We will release the next version

**Comment by AugustToko** [comment]
try new version
