### ISSUE TITLE
Sho detail option does not work when a song is being played

### ISSUE THREAD

**Issue by crysports** [AugustToko/ACG-Player#48]
There is an option of show detail when you click on the menu option on a currently played song. When you click on it, you see a blank screen. No details are shown.
https://youtu.be/HQ0ZViru604

**Comment by AugustToko** [comment]
Are you downloading the latest version?

**Comment by crysports** [comment]
Yes

**Comment by AugustToko** [comment]
https://github.com/AugustToko/ACG-Player/releases/tag/2.6.5.4(20190601)
