### ISSUE TITLE
App crashes if i try to play song on notification bar

### ISSUE THREAD

**Issue by lushohammy** [AugustToko/ACG-Player#5]
**Describe the bug**
when playing a music and i tring to play or next song in notification bar it shows me stooped.

**To Reproduce**
1. Download the app and open it
2. then play a music
3. then click back button and exit from app
4. then try to listen next song click on next button from notification bar

**Expected behavior**
I expected that the app would not crash when I click on next button from notification bar

**Device:**
 - OS: Android 8.1.0
 - appVersion 2.6.2.5

**Recording Of The Bug:**
https://youtu.be/1T3yl4Qi6uk

**Comment by AugustToko** [comment]
This is an IPC issue that will be fixed in the near future, thank you for your report.

**Comment by AugustToko** [comment]
I think he has been fixed and will be posted to the release page later.
