### ISSUE TITLE
App neither plays nor repeat the next song 

### ISSUE THREAD

**Issue by cckole** [AugustToko/ACG-Player#55]
**Describe the bug**
Each time I play a song and it ends, It stops playing further.

**To Reproduce**
1. Launch the app
2. Play a song
3. Allow it to finish playing

**Expected behavior**
I expected the next song to play when the recent one finishes or replay the just concluded one with respect to the single/play next settings.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Tecno spark 7.0]
 - OS: [Android 7.0]

**Additional context**
I think why this problem occurs is the fact that the single/next icons isn't working. I believe once that is fixed, the play nex or repeat should pick up.

**Comment by cckole** [comment]
I closed it because it works well after totally deleting the app and reinstalling it. Maybe you should advice contributors to uninstall before insatlling every new version you release.

**Comment by AugustToko** [comment]
Currently, the project often changes a lot, and many of the key-value pairs are not forward compatible. When I change it, he will not work properly in the new version. This is one of my negligence. I will be compatible in future versions.
Thank you for your interest in this project.

**Comment by cckole** [comment]
You are welcome.
