### ISSUE TITLE
App crashed when I clicked on show details on a song being played

### ISSUE THREAD

**Issue by crysports** [AugustToko/ACG-Player#57]
I clicked on show details option on a song which I was playing and the application crashed.
I tried multiple times but the result was same.
Video of the bug
https://youtu.be/dOkFSJ0fV2M
App version: 2.6.5.9

**Comment by AugustToko** [comment]
Ok, fix this bug later, the crash caused by the null pointer

**Comment by AugustToko** [comment]
fixed try new version (release page)
