### ISSUE TITLE
Song added to favourite more than once.

### ISSUE THREAD

**Issue by cckole** [AugustToko/ACG-Player#58]
**Describe the bug**
When I add the same song to favourite more than one time, it keeps adding. This means if I add it twenty times, I will have 20 lists that particular song in favourites.

**To Reproduce**
1. Launch the app
2. Click on music
3. click on the three dots opposite any song 
4. click on `add to playlist`
5. click on favourite.
6. Add the same song to favourite as much time as you can
7. check the favourite, you will see the same song listed

**Expected behavior**
I expected the song to only add once and display a note that it has been already added on second or subsequent addition.

**Screenshots**
![Screenshot_20190602-192228](https://user-images.githubusercontent.com/36272218/58765627-dbacae00-856c-11e9-9bbd-e1069a58f24e.png)

**Smartphone (please complete the following information):**
 - Device: [tecno spark k7]
 - OS: [Android 7.0]
 - Version [2.6.5.9]

**Comment by AugustToko** [comment]
Delete this playlist and re-add it. This is a legacy issue with a previous version of the bug.

**Comment by cckole** [comment]
I just did that and the app crashed every time I tried to add a song to playlist. I can see an [isssue](https://github.com/AugustToko/ACG-Player/issues/56)  has been opened already for this.

**Comment by AugustToko** [comment]
try new version on release page.
I added a log function to it, which can record crashes and then send them to the cloud. So I can locate the cause of the crash.

**Comment by cckole** [comment]
That's a nice approach. I love it.

**Comment by AugustToko** [comment]
Try the new version (release page), it may have been fixed
