### ISSUE TITLE
[Acg Player][v2.6.2]App failed to play song from playlist. 

### ISSUE THREAD

**Issue by maaudrana** [AugustToko/ACG-Player#6]
<h4>Actual behavior</h4>
App crashes if i want to play music from playlist.
<h4>Expected behavior</h4>
Expected that i can play song from playlist.
<h4>How to reproduce</h4>
<ol>
<li>Install the apps and open the app</li>
<li>Navigate to playlist</li>
<li>click any playlist</li>
<li>Click any song to play</li>
<li>See the error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:v2.6.2</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/H8ZCfDxyGcU">https://youtu.be/H8ZCfDxyGcU</a>
<h4>Logcat</h4>
<pre><code>
05-24 15:24:36.450 18905 18905 E AndroidRuntime: FATAL EXCEPTION: main
05-24 15:24:36.450 18905 18905 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 18905
05-24 15:24:36.450 18905 18905 E AndroidRuntime: java.lang.IllegalArgumentException: bound must be positive
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at java.util.Random.nextInt(Random.java:388)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.activity.ListViewActivity.d(SourceFile:32)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at h.a.a.b.a.L.onMenuItemClick(Unknown Source:2)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(SourceFile:2)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(SourceFile:2)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at b.b.f.a.k.a(SourceFile:19)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at b.b.f.a.o.invoke(SourceFile:2)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at b.b.f.a.k.a(SourceFile:39)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at b.b.f.a.k.a(SourceFile:36)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at androidx.appcompat.widget.ActionMenuView.invokeItem(SourceFile:1)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(SourceFile:2)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at android.view.View.performClick(View.java:7339)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:14222)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7305)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at android.view.View.access$3200(View.java:846)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27788)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

</code></pre>

**Comment by maaudrana** [comment]
Is this issue fixed? 
Or can you pls give feedback for #8 issue,not here on the issue  pls.

**Comment by AugustToko** [comment]
You can try the latest version on the release page.

**Comment by maaudrana** [comment]
Ah dear working fine
