### ISSUE TITLE
Deleting song from trash crashes the app

### ISSUE THREAD

**Issue by crysports** [AugustToko/ACG-Player#60]
I moved a song to the trash and tried to delete it from there.
What I noticed was that when I clicked on delete, the song was still present there but when I clicked delete second time, the application crashed. 
I tried a few times but the result was the same.
I tried it new version as you suggested to download it.
I think you also would have got the crash report.
I will attach a video link below

https://youtu.be/EabiT4rSFtg

**Comment by crysports** [comment]
Have you located this one?

**Comment by AugustToko** [comment]
> Have you located this one?

fixed!!!! i will push into release page

**Comment by AugustToko** [comment]
> > Have you located this one?
> 
> fixed!!!! i will push into release page

I am sorry to fix this late, I am going to reset my linux web server these few days.

**Comment by AugustToko** [comment]
uploaded
