### ISSUE TITLE
After clicking on "Shuffle" option in Trash Bin. App gets crashed.

### ISSUE THREAD

**Issue by Xeeshuu** [AugustToko/ACG-Player#63]
After opening the app i go to "Trash Bin" , where i clicked on "Shuffle"(cross arrows), app got crashed.
**SCREENSHOT**
![20190609_120842](https://user-images.githubusercontent.com/37048348/59155872-6df20c00-8aaf-11e9-8405-a0945a5f4d0a.gif)

**Comment by AugustToko** [comment]
Ok, I will fix it.

**Comment by Xeeshuu** [comment]
> Ok, I will fix it.

Ok, thank you.

**Comment by Xeeshuu** [comment]
> Ok, I will fix it.

Ok thank you...
