### ISSUE TITLE
ACG-Player v2.6.6(20190607): Unable to play another song after checking out a playlist.

### ISSUE THREAD

**Issue by HarryHeights** [AugustToko/ACG-Player#64]
**Describe the bug**
The app gets kind of frozen. The actions that led the app to get frozen is quite weird. I launched the app, play a song, checked out the playlist menu, opened a playlist and that was it. I could still navigate through the app, but I couldn't play another song. The only way to restore things to normalcy was by exiting the app. 

**To Reproduce**
1. Launch the app and play a song or not.
2. Access the playlist page
3. Open a playlist if you have one. If you don't, just open the trash can
4. Go back to your song list
5. Try to play another song.
6. See error.

**Expected behavior**
The expected behaviour from my series of actions is pretty much straight-forward. I expected that I could play a song at any time on the app, regardless of any other action I perform within the confines of the app. 

**Screen recording**
https://www.youtube.com/watch?v=oHaaEXV6KUA

**Test Environment:**
 - Device: Redmi Note 5 Pro
 - OS: Android 9.0
 - Software version: ACG-Player v2.6.6(20190607)

**Comment by AugustToko** [comment]
Try Latest release on release page, i think it fixed, because I have encountered this problem before.

**Comment by HarryHeights** [comment]
It is fixed now. Thanks.
