### ISSUE TITLE
App crashes when i change the layout of albums from Grid to Linear.

### ISSUE THREAD

**Issue by Xeeshuu** [AugustToko/ACG-Player#67]
After opening the app, i goes to album folder and then i clicked on options where i saw "album layout" option. I clicked on it to change the layout, i changed it from Grid to Linear. App got crashed. Not only app crashes, i am not able to open it agin untill i clear its whole data.
**Screenshot/Video**
![20190614_090851](https://user-images.githubusercontent.com/37048348/59481973-5c7c7b80-8e84-11e9-923a-8954afaa8c4c.gif)
**System Information:**
* Device: RedMi S2/Y2.
* OS: 8.1.0
* Version: 2.6.6.8(20190608)

**Comment by AugustToko** [comment]
try lastest version on release page

**Comment by Xeeshuu** [comment]
> try lastest version on release page

I tried latest version
But it also has same issue...

**Comment by AugustToko** [comment]
> > try lastest version on release page
> 
> I tried latest version
> But it also has same issue...

Can you give me a log? This feature works fine on both of my devices.

**Comment by Xeeshuu** [comment]
It is working properly.

**Comment by Xeeshuu** [comment]
It is working properly.
