### ISSUE TITLE
App crashes when I turn off the storage permission

### ISSUE THREAD

**Issue by iamowomizz** [AugustToko/ACG-Player#68]
**Describe the bug**
The app crashes when I turn off the storage permission

**To Reproduce**
1. Launch the app
2. Accept all permissions
3. Then go to the application details of the ACG player app
4. Turn off the storage permission

**Expected behavior**
I expected the app not to crash when I turn off The storage permission

Devices and Versions
Device: (Infinix s2pro)
Version (7.0)
App version (2.6.7.4)

**Comment by AugustToko** [comment]
try lastest version on release page
