### ISSUE TITLE
Music share Bug on Android v8.1.0

### ISSUE THREAD

**Issue by lushohammy** [AugustToko/ACG-Player#7]
**Describe the bug**
app crashes when click on share .

**To Reproduce**
1. open the app
2. try to share music from home page
3. note the bug.

**Expected behavior**
I expected that the app would not crash when I click on "share"option.

**Device:**
 
 - OS: Android 8.1.0
 - appVersion 2.6.2.5

**Recording Of The Bug:**
https://youtu.be/cbUmXtahWI4

**Comment by AugustToko** [comment]
You can try it with the new version, this function works fine on my device, or you can grab the log
