### ISSUE TITLE
"Timer" gets automatically opened when clicked on "EQ" option.

### ISSUE THREAD

**Issue by Xeeshuu** [AugustToko/ACG-Player#71]
When i opened the app and played a song.
I clicked on "options" and then clicked on "EQ" option. Timer gets automatically opened.
**Video/Screenshot:**
https://youtu.be/IbH7j3SbDVQ
**Device:**
* Android: RedMi Y2/S2
* OS: 8.1.0
* version: 2.6.8.0(20190617)-prerelease

**Comment by AugustToko** [comment]
fixed, on release page
