### ISSUE TITLE
EQ option is not working.

### ISSUE THREAD

**Issue by Xeeshuu** [AugustToko/ACG-Player#72]
"EQ" option is not working when clicking on it.
**Video/Screenshot:**
https://youtu.be/OHTT_Nq6Xvg
**Device Information:**
* Android: RedMi Y2/S2.
* OS: 8.1.0
* App Version: 2.6.8.2(20190618)-prerelease

**Comment by AugustToko** [comment]
see #39

**Comment by Xeeshuu** [comment]
@AugustToko before this version, it works properly..

**Comment by AugustToko** [comment]
try lastest version

**Comment by Xeeshuu** [comment]
@AugustToko not working in latest version too.... See this video:https://youtu.be/QzrjLQiL5xI

**Comment by AugustToko** [comment]
https://github.com/AugustToko/ACG-Player/releases/tag/2.6.8.5(20190619)

**Comment by Xeeshuu** [comment]
Working in new release.

**Comment by AugustToko** [comment]
done
