### ISSUE TITLE
App crashes when Timer is set to 00:00.

### ISSUE THREAD

**Issue by Xeeshuu** [AugustToko/ACG-Player#73]
After opening the app, i streamed songs and then clicked on "Timer" option. Then set "Timer" to 00:00 and clicked on "OK". After clicking on it app got crashed.
**Video/Screenshot:**
https://youtu.be/uWqeP7Dat_4
**Device:**
* Android: RedMi Y2/S2
* OS:8.1.0
* Version: 2.6.8.3(20190619)

**Comment by AugustToko** [comment]
may fixed, on release page, If you set it to another time it works?

**Comment by Xeeshuu** [comment]
@AugustToko it works when set to another time but stops when set to 00:00

**Comment by AugustToko** [comment]
> @AugustToko it works when set to another time but stops when set to 00:00

Try the latest version Is it still crash?

**Comment by Xeeshuu** [comment]
> > @AugustToko it works when set to another time but stops when set to 00:00
> 
> Try the latest version Is it still crash?

Yes, it still crashes.

**Comment by AugustToko** [comment]
The reason for the flashback is that opening EQ requires a music that is playing, obviously you have not done so.
I will add this prompt

**Comment by AugustToko** [comment]
> > > @AugustToko it works when set to another time but stops when set to 00:00
> > 
> > 
> > Try the latest version Is it still crash?
> 
> Yes, it still crashes.

The reason for the flashback is that setting the timer requires a music that is playing, obviously you have not done so.
I will add this prompt

**Comment by Xeeshuu** [comment]
It stops music when it is set to 00:00. While playing

**Comment by AugustToko** [comment]
can you give me a log?
![image](https://user-images.githubusercontent.com/20200460/59760353-b4701380-92c4-11e9-9cca-ce5c26c6fd0c.png)

**Comment by AugustToko** [comment]
gan you give me a log？
when crash , click repot botton

**Comment by Xeeshuu** [comment]
I am not able to get log...

**Comment by AugustToko** [comment]
try this https://github.com/AugustToko/ACG-Player/releases/tag/2.6.8.6(20190619)

**Comment by Xeeshuu** [comment]
Now working....
