### ISSUE TITLE
App crashes when song is deleted from trash can.

### ISSUE THREAD

**Issue by Xeeshuu** [AugustToko/ACG-Player#79]
I played a song and then add it to trash bin twice from clicking on 3 dots on top right corner and from 3 dots mentioned on right side of the song. After that when going to Trsh Bin and i deleted them from Trash Bin.  App got crashed when deleted both of them.
**Video/Screenshot:**
https://youtu.be/SMeqPYkGvrQ
**Device:**
* Android:RedMi Y2/S2
* OS: 8.1.0
* App version: 2.6.9.0(20190621)

**Comment by AugustToko** [comment]
The trash can was removed in the new version. Can you delete the song in other places?

**Comment by Xeeshuu** [comment]
Ok i will try...
