### ISSUE TITLE
[Acg player][v2.6.2]The  app crashes if i try to add song to playlist. 

### ISSUE THREAD

**Issue by maaudrana** [AugustToko/ACG-Player#8]
<h4>Actual behavior</h4>
App crashes if i try to add song to playlist.
<h4>Expected behavior</h4>
Expected that i can add to playlist.
<h4>How to reproduce</h4>
<ol>
<li>Install the apps and open the app</li>
<li>From Music Navigation ,click any song to play</li>
<li>Then click click the song icon you just played</li>
<li>Scroll down and choose anys song</li>
<li>Click three horizontal dot</li>
<li>From the option list, click the 2nd option</li>
<li>Choose playlist to add the song</li>
<li>Click the playlist</li>
<li>see the error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:v2.6.2</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/fibfGiUxd1w">https://youtu.be/fibfGiUxd1w</a>
<h4>Logcat</h4>
<pre><code>
05-24 15:28:07.608 21952 21952 E AndroidRuntime: FATAL EXCEPTION: main
05-24 15:28:07.608 21952 21952 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 21952
05-24 15:28:07.608 21952 21952 E AndroidRuntime: java.lang.IllegalArgumentException: bound must be positive
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at java.util.Random.nextInt(Random.java:388)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.activity.ListViewActivity.d(SourceFile:32)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at h.a.a.b.a.L.onMenuItemClick(Unknown Source:2)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(SourceFile:2)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(SourceFile:2)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at b.b.f.a.k.a(SourceFile:19)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at b.b.f.a.o.invoke(SourceFile:2)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at b.b.f.a.k.a(SourceFile:39)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at b.b.f.a.k.a(SourceFile:36)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at androidx.appcompat.widget.ActionMenuView.invokeItem(SourceFile:1)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(SourceFile:2)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at android.view.View.performClick(View.java:7339)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:14222)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7305)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at android.view.View.access$3200(View.java:846)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27788)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-24 15:28:07.608 21952 21952 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-24 15:24:36.450 18905 18905 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
</code>
</pre>

**Comment by AugustToko** [comment]
Upgrade to the latest version (on the release page) and recheck it

**Comment by maaudrana** [comment]
Ah working  fine in latest versions👏👏👏Just checked that.

**Comment by AugustToko** [comment]
ok i will close this issue
