### ISSUE TITLE
Timer is not working when music is being played in Car Mode.

### ISSUE THREAD

**Issue by Xeeshuu** [AugustToko/ACG-Player#80]
I played a song and then turned it to Car Mode. After that i clicked on 3 dots on the top right corner of the page. Then i clicked on Timer option. It is not working.
**Video/Screenshot:**
https://youtu.be/czJ_qa6Rw34
**Device:**
* Android: RedMi Y2/S2
* OS: 8.1.0
* App Version: 2.6.9.0(20190621)

**Comment by AugustToko** [comment]
Fixed, see the lastest on release page.
