### ISSUE TITLE
(BUG) Found in ACG-Player The application crashes when I click on NEXT play

### ISSUE THREAD

**Issue by saraji-ali** [AugustToko/ACG-Player#9]
# Project Information

* Repository: https://github.com/AugustToko/ACG-Player
* Project Name:  ACG-Player

# Expected behavior

When I click on the Nextplay button, the Next Song should be played

# Actual behavior

 The application crashes when I click on NEXT play

# How to reproduce

1-[Download ](https://github.com/AugustToko/ACG-Player/releases)the app and open it
2- click on 3 verticle dots
3- click on Next play option
4- see bug 

* Browser/App version: 2.6.2.5
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug
![20190524_161102](https://user-images.githubusercontent.com/50115498/58324022-83daae00-7dda-11e9-8c2e-70334bbfba13.gif)

# My Github Account
https://github.com/saraji-ali

# Logcat

<pre><code>E/AndroidRuntime(18657): FATAL EXCEPTION: AsyncTask #2

E/AndroidRuntime(18657): Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 18657

E/AndroidRuntime(18657): java.lang.RuntimeException: An error occured while executing doInBackground()

E/AndroidRuntime(18657): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)

E/AndroidRuntime(18657): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)

E/AndroidRuntime(18657): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)

E/AndroidRuntime(18657): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)

E/AndroidRuntime(18657): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)

E/AndroidRuntime(18657): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

E/AndroidRuntime(18657): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

E/AndroidRuntime(18657): 	at java.lang.Thread.run(Thread.java:818)

E/AndroidRuntime(18657): Caused by: java.lang.IllegalStateException: Can't call getPixel() on a recycled bitmap

E/AndroidRuntime(18657): 	at android.graphics.Bitmap.checkRecycled(Bitmap.java:352)

E/AndroidRuntime(18657): 	at android.graphics.Bitmap.getPixel(Bitmap.java:1580)

E/AndroidRuntime(18657): 	at h.a.a.b.h.o.t(SourceFile:3)

E/AndroidRuntime(18657): 	at h.a.a.b.d.Ta.a(SourceFile:1)

E/AndroidRuntime(18657): 	at h.a.a.b.d.Ta.doInBackground(SourceFile:1)

E/AndroidRuntime(18657): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)

E/AndroidRuntime(18657): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

E/AndroidRuntime(18657): 	... 4 more
</code></pre>

**Comment by AugustToko** [comment]
You can try the latest version on the release page.It should have been fixed

**Comment by saraji-ali** [comment]
thank you sir bug has been fixed
